/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1,
  SWIG_JavaIOException,
  SWIG_JavaRuntimeException,
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError,
  SWIG_JavaIllegalStateException,
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { SWIG_JavaIllegalStateException, "java/lang/IllegalStateException" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "../include/Channel.h"
#include "../include/Config.h"
#include "../include/Video.h"
#include "../include/List.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void JNICALL Java_uk_co_therhys_LibYT_ytJNI_Channel_1t_1id_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  struct Channel *arg1 = (struct Channel *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Channel **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    free(arg1->id);
    if (arg2) {
      arg1->id = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->id, (const char *)arg2);
    } else {
      arg1->id = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_uk_co_therhys_LibYT_ytJNI_Channel_1t_1id_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jstring jresult = 0 ;
  struct Channel *arg1 = (struct Channel *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Channel **)&jarg1; 
  result = (char *) ((arg1)->id);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_uk_co_therhys_LibYT_ytJNI_Channel_1t_1name_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  struct Channel *arg1 = (struct Channel *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Channel **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    free(arg1->name);
    if (arg2) {
      arg1->name = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->name, (const char *)arg2);
    } else {
      arg1->name = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_uk_co_therhys_LibYT_ytJNI_Channel_1t_1name_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jstring jresult = 0 ;
  struct Channel *arg1 = (struct Channel *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Channel **)&jarg1; 
  result = (char *) ((arg1)->name);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_uk_co_therhys_LibYT_ytJNI_Channel_1t_1sub_1count_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  struct Channel *arg1 = (struct Channel *) 0 ;
  long arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Channel **)&jarg1; 
  arg2 = (long)jarg2; 
  if (arg1) (arg1)->sub_count = arg2;
}


SWIGEXPORT jint JNICALL Java_uk_co_therhys_LibYT_ytJNI_Channel_1t_1sub_1count_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct Channel *arg1 = (struct Channel *) 0 ;
  long result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Channel **)&jarg1; 
  result = (long) ((arg1)->sub_count);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_uk_co_therhys_LibYT_ytJNI_Channel_1t_1video_1count_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  struct Channel *arg1 = (struct Channel *) 0 ;
  long arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Channel **)&jarg1; 
  arg2 = (long)jarg2; 
  if (arg1) (arg1)->video_count = arg2;
}


SWIGEXPORT jint JNICALL Java_uk_co_therhys_LibYT_ytJNI_Channel_1t_1video_1count_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct Channel *arg1 = (struct Channel *) 0 ;
  long result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Channel **)&jarg1; 
  result = (long) ((arg1)->video_count);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_uk_co_therhys_LibYT_ytJNI_new_1Channel_1t(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct Channel *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct Channel *)calloc(1, sizeof(struct Channel));
  *(struct Channel **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_uk_co_therhys_LibYT_ytJNI_delete_1Channel_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct Channel *arg1 = (struct Channel *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Channel **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_uk_co_therhys_LibYT_ytJNI_Channels_1t_1arry_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  struct Channels *arg1 = (struct Channels *) 0 ;
  Channel_t **arg2 = (Channel_t **) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Channels **)&jarg1; 
  arg2 = *(Channel_t ***)&jarg2; 
  if (arg1) (arg1)->arry = arg2;
}


SWIGEXPORT jlong JNICALL Java_uk_co_therhys_LibYT_ytJNI_Channels_1t_1arry_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct Channels *arg1 = (struct Channels *) 0 ;
  Channel_t **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Channels **)&jarg1; 
  result = (Channel_t **) ((arg1)->arry);
  *(Channel_t ***)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_uk_co_therhys_LibYT_ytJNI_Channels_1t_1length_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  struct Channels *arg1 = (struct Channels *) 0 ;
  long arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Channels **)&jarg1; 
  arg2 = (long)jarg2; 
  if (arg1) (arg1)->length = arg2;
}


SWIGEXPORT jint JNICALL Java_uk_co_therhys_LibYT_ytJNI_Channels_1t_1length_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct Channels *arg1 = (struct Channels *) 0 ;
  long result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Channels **)&jarg1; 
  result = (long) ((arg1)->length);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_uk_co_therhys_LibYT_ytJNI_new_1Channels_1t(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct Channels *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct Channels *)calloc(1, sizeof(struct Channels));
  *(struct Channels **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_uk_co_therhys_LibYT_ytJNI_delete_1Channels_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct Channels *arg1 = (struct Channels *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Channels **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jlong JNICALL Java_uk_co_therhys_LibYT_ytJNI_channel_1new(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  Channel_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (Channel_t *)channel_new((char const *)arg1);
  *(Channel_t **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_uk_co_therhys_LibYT_ytJNI_vid_1get_1thumbnail(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jstring jresult = 0 ;
  void *arg1 = (void *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  result = (char *)vid_get_thumbnail(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_uk_co_therhys_LibYT_ytJNI_channel_1new_1from_1name(JNIEnv *jenv, jclass jcls, jstring jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  Config_t *arg2 = (Config_t *) 0 ;
  Channel_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = *(Config_t **)&jarg2; 
  result = (Channel_t *)channel_new_from_name((char const *)arg1,arg2);
  *(Channel_t **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT void JNICALL Java_uk_co_therhys_LibYT_ytJNI_channel_1search(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jint jarg3, jlong jarg4, jlong jarg5) {
  Config_t *arg1 = (Config_t *) 0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  channel_cb arg4 = (channel_cb) 0 ;
  void *arg5 = (void *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Config_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  arg3 = (int)jarg3; 
  arg4 = *(channel_cb *)&jarg4; 
  arg5 = *(void **)&jarg5; 
  channel_search(arg1,(char const *)arg2,arg3,arg4,arg5);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jlong JNICALL Java_uk_co_therhys_LibYT_ytJNI_channel_1search_1list(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jint jarg3) {
  jlong jresult = 0 ;
  Config_t *arg1 = (Config_t *) 0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  List_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Config_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (int)jarg3; 
  result = (List_t *)channel_search_list(arg1,(char const *)arg2,arg3);
  *(List_t **)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_uk_co_therhys_LibYT_ytJNI_channel_1name(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jstring jresult = 0 ;
  Channel_t *arg1 = (Channel_t *) 0 ;
  Config_t *arg2 = (Config_t *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Channel_t **)&jarg1; 
  arg2 = *(Config_t **)&jarg2; 
  result = (char *)channel_name(arg1,arg2);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_uk_co_therhys_LibYT_ytJNI_channel_1get_1vids(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  Channel_t *arg1 = (Channel_t *) 0 ;
  Config_t *arg2 = (Config_t *) 0 ;
  vid_cb arg3 = (vid_cb) 0 ;
  void *arg4 = (void *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Channel_t **)&jarg1; 
  arg2 = *(Config_t **)&jarg2; 
  arg3 = *(vid_cb *)&jarg3; 
  arg4 = *(void **)&jarg4; 
  result = (int)channel_get_vids(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_uk_co_therhys_LibYT_ytJNI_channel_1get_1vids_1list(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  Channel_t *arg1 = (Channel_t *) 0 ;
  Config_t *arg2 = (Config_t *) 0 ;
  List_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Channel_t **)&jarg1; 
  arg2 = *(Config_t **)&jarg2; 
  result = (List_t *)channel_get_vids_list(arg1,arg2);
  *(List_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_uk_co_therhys_LibYT_ytJNI_channel_1free(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Channel_t *arg1 = (Channel_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Channel_t **)&jarg1; 
  channel_free(arg1);
}


SWIGEXPORT void JNICALL Java_uk_co_therhys_LibYT_ytJNI_Config_1t_1fname_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  struct Config *arg1 = (struct Config *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Config **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if (arg2) {
      arg1->fname = (char const *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->fname, (const char *)arg2);
    } else {
      arg1->fname = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_uk_co_therhys_LibYT_ytJNI_Config_1t_1fname_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jstring jresult = 0 ;
  struct Config *arg1 = (struct Config *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Config **)&jarg1; 
  result = (char *) ((arg1)->fname);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_uk_co_therhys_LibYT_ytJNI_Config_1t_1quality_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  struct Config *arg1 = (struct Config *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Config **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->quality = arg2;
}


SWIGEXPORT jint JNICALL Java_uk_co_therhys_LibYT_ytJNI_Config_1t_1quality_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct Config *arg1 = (struct Config *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Config **)&jarg1; 
  result = (int) ((arg1)->quality);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_uk_co_therhys_LibYT_ytJNI_Config_1t_1subs_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  struct Config *arg1 = (struct Config *) 0 ;
  struct List *arg2 = (struct List *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Config **)&jarg1; 
  arg2 = *(struct List **)&jarg2; 
  if (arg1) (arg1)->subs = arg2;
}


SWIGEXPORT jlong JNICALL Java_uk_co_therhys_LibYT_ytJNI_Config_1t_1subs_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct Config *arg1 = (struct Config *) 0 ;
  struct List *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Config **)&jarg1; 
  result = (struct List *) ((arg1)->subs);
  *(struct List **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_uk_co_therhys_LibYT_ytJNI_Config_1t_1invidious_1inst_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  struct Config *arg1 = (struct Config *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Config **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if (arg2) {
      arg1->invidious_inst = (char const *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->invidious_inst, (const char *)arg2);
    } else {
      arg1->invidious_inst = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_uk_co_therhys_LibYT_ytJNI_Config_1t_1invidious_1inst_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jstring jresult = 0 ;
  struct Config *arg1 = (struct Config *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Config **)&jarg1; 
  result = (char *) ((arg1)->invidious_inst);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_uk_co_therhys_LibYT_ytJNI_Config_1t_1use_1threading_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  struct Config *arg1 = (struct Config *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Config **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->use_threading = arg2;
}


SWIGEXPORT jint JNICALL Java_uk_co_therhys_LibYT_ytJNI_Config_1t_1use_1threading_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct Config *arg1 = (struct Config *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Config **)&jarg1; 
  result = (int) ((arg1)->use_threading);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_uk_co_therhys_LibYT_ytJNI_Config_1t_1use_1proxy_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  struct Config *arg1 = (struct Config *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Config **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->use_proxy = arg2;
}


SWIGEXPORT jint JNICALL Java_uk_co_therhys_LibYT_ytJNI_Config_1t_1use_1proxy_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct Config *arg1 = (struct Config *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Config **)&jarg1; 
  result = (int) ((arg1)->use_proxy);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_uk_co_therhys_LibYT_ytJNI_Config_1t_1proxy_1url_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  struct Config *arg1 = (struct Config *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Config **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if (arg2) {
      arg1->proxy_url = (char const *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->proxy_url, (const char *)arg2);
    } else {
      arg1->proxy_url = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_uk_co_therhys_LibYT_ytJNI_Config_1t_1proxy_1url_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jstring jresult = 0 ;
  struct Config *arg1 = (struct Config *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Config **)&jarg1; 
  result = (char *) ((arg1)->proxy_url);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_uk_co_therhys_LibYT_ytJNI_new_1Config_1t(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct Config *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct Config *)calloc(1, sizeof(struct Config));
  *(struct Config **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_uk_co_therhys_LibYT_ytJNI_delete_1Config_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct Config *arg1 = (struct Config *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Config **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jlong JNICALL Java_uk_co_therhys_LibYT_ytJNI_config_1new(JNIEnv *jenv, jclass jcls, jstring jarg1, jint jarg2) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  int arg2 ;
  Config_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = (int)jarg2; 
  result = (Config_t *)config_new((char const *)arg1,arg2);
  *(Config_t **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT void JNICALL Java_uk_co_therhys_LibYT_ytJNI_config_1subs_1add(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  Config_t *arg1 = (Config_t *) 0 ;
  Channel_t *arg2 = (Channel_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Config_t **)&jarg1; 
  arg2 = *(Channel_t **)&jarg2; 
  config_subs_add(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_uk_co_therhys_LibYT_ytJNI_config_1subs_1rm(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  Config_t *arg1 = (Config_t *) 0 ;
  Channel_t *arg2 = (Channel_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Config_t **)&jarg1; 
  arg2 = *(Channel_t **)&jarg2; 
  config_subs_rm(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_uk_co_therhys_LibYT_ytJNI_config_1save(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Config_t *arg1 = (Config_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Config_t **)&jarg1; 
  config_save(arg1);
}


SWIGEXPORT jlong JNICALL Java_uk_co_therhys_LibYT_ytJNI_config_1get_1vids_1list(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  Config_t *arg1 = (Config_t *) 0 ;
  List_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Config_t **)&jarg1; 
  result = (List_t *)config_get_vids_list(arg1);
  *(List_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_uk_co_therhys_LibYT_ytJNI_config_1get_1vids(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jint jresult = 0 ;
  Config_t *arg1 = (Config_t *) 0 ;
  vid_cb arg2 = (vid_cb) 0 ;
  void *arg3 = (void *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Config_t **)&jarg1; 
  arg2 = *(vid_cb *)&jarg2; 
  arg3 = *(void **)&jarg3; 
  result = (int)config_get_vids(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_uk_co_therhys_LibYT_ytJNI_video_1get_1playable(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jstring jresult = 0 ;
  Video_t *arg1 = (Video_t *) 0 ;
  Config_t *arg2 = (Config_t *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Video_t **)&jarg1; 
  arg2 = *(Config_t **)&jarg2; 
  result = (char *)video_get_playable(arg1,arg2);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_uk_co_therhys_LibYT_ytJNI_config_1free(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Config_t *arg1 = (Config_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Config_t **)&jarg1; 
  config_free(arg1);
}


SWIGEXPORT void JNICALL Java_uk_co_therhys_LibYT_ytJNI_config_1video_1search(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jint jarg3, jlong jarg4, jlong jarg5) {
  Config_t *arg1 = (Config_t *) 0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  vid_cb arg4 = (vid_cb) 0 ;
  void *arg5 = (void *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Config_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  arg3 = (int)jarg3; 
  arg4 = *(vid_cb *)&jarg4; 
  arg5 = *(void **)&jarg5; 
  config_video_search(arg1,(char const *)arg2,arg3,arg4,arg5);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jlong JNICALL Java_uk_co_therhys_LibYT_ytJNI_config_1video_1search_1list(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jint jarg3) {
  jlong jresult = 0 ;
  Config_t *arg1 = (Config_t *) 0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  List_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Config_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (int)jarg3; 
  result = (List_t *)config_video_search_list(arg1,(char const *)arg2,arg3);
  *(List_t **)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT void JNICALL Java_uk_co_therhys_LibYT_ytJNI_Video_1t_1id_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  struct Video *arg1 = (struct Video *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Video **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    free(arg1->id);
    if (arg2) {
      arg1->id = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->id, (const char *)arg2);
    } else {
      arg1->id = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_uk_co_therhys_LibYT_ytJNI_Video_1t_1id_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jstring jresult = 0 ;
  struct Video *arg1 = (struct Video *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Video **)&jarg1; 
  result = (char *) ((arg1)->id);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_uk_co_therhys_LibYT_ytJNI_Video_1t_1title_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  struct Video *arg1 = (struct Video *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Video **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    free(arg1->title);
    if (arg2) {
      arg1->title = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->title, (const char *)arg2);
    } else {
      arg1->title = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_uk_co_therhys_LibYT_ytJNI_Video_1t_1title_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jstring jresult = 0 ;
  struct Video *arg1 = (struct Video *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Video **)&jarg1; 
  result = (char *) ((arg1)->title);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_uk_co_therhys_LibYT_ytJNI_Video_1t_1channel_1name_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  struct Video *arg1 = (struct Video *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Video **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    free(arg1->channel_name);
    if (arg2) {
      arg1->channel_name = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->channel_name, (const char *)arg2);
    } else {
      arg1->channel_name = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_uk_co_therhys_LibYT_ytJNI_Video_1t_1channel_1name_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jstring jresult = 0 ;
  struct Video *arg1 = (struct Video *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Video **)&jarg1; 
  result = (char *) ((arg1)->channel_name);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_uk_co_therhys_LibYT_ytJNI_Video_1t_1channel_1id_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  struct Video *arg1 = (struct Video *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Video **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    free(arg1->channel_id);
    if (arg2) {
      arg1->channel_id = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->channel_id, (const char *)arg2);
    } else {
      arg1->channel_id = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_uk_co_therhys_LibYT_ytJNI_Video_1t_1channel_1id_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jstring jresult = 0 ;
  struct Video *arg1 = (struct Video *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Video **)&jarg1; 
  result = (char *) ((arg1)->channel_id);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_uk_co_therhys_LibYT_ytJNI_Video_1t_1thumbnail_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  struct Video *arg1 = (struct Video *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Video **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    free(arg1->thumbnail);
    if (arg2) {
      arg1->thumbnail = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->thumbnail, (const char *)arg2);
    } else {
      arg1->thumbnail = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_uk_co_therhys_LibYT_ytJNI_Video_1t_1thumbnail_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jstring jresult = 0 ;
  struct Video *arg1 = (struct Video *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Video **)&jarg1; 
  result = (char *) ((arg1)->thumbnail);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_uk_co_therhys_LibYT_ytJNI_Video_1t_1published_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  struct Video *arg1 = (struct Video *) 0 ;
  long arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Video **)&jarg1; 
  arg2 = (long)jarg2; 
  if (arg1) (arg1)->published = arg2;
}


SWIGEXPORT jint JNICALL Java_uk_co_therhys_LibYT_ytJNI_Video_1t_1published_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct Video *arg1 = (struct Video *) 0 ;
  long result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Video **)&jarg1; 
  result = (long) ((arg1)->published);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_uk_co_therhys_LibYT_ytJNI_new_1Video_1t(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct Video *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct Video *)calloc(1, sizeof(struct Video));
  *(struct Video **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_uk_co_therhys_LibYT_ytJNI_delete_1Video_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct Video *arg1 = (struct Video *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Video **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jlong JNICALL Java_uk_co_therhys_LibYT_ytJNI_video_1new(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  Video_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (Video_t *)video_new();
  *(Video_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_uk_co_therhys_LibYT_ytJNI_video_1free(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Video_t *arg1 = (Video_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Video_t **)&jarg1; 
  video_free(arg1);
}


SWIGEXPORT void JNICALL Java_uk_co_therhys_LibYT_ytJNI_List_1t_1arry_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  struct List *arg1 = (struct List *) 0 ;
  void **arg2 = (void **) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct List **)&jarg1; 
  arg2 = *(void ***)&jarg2; 
  if (arg1) (arg1)->arry = arg2;
}


SWIGEXPORT jlong JNICALL Java_uk_co_therhys_LibYT_ytJNI_List_1t_1arry_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct List *arg1 = (struct List *) 0 ;
  void **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct List **)&jarg1; 
  result = (void **) ((arg1)->arry);
  *(void ***)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_uk_co_therhys_LibYT_ytJNI_List_1t_1length_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  struct List *arg1 = (struct List *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct List **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->length = arg2;
}


SWIGEXPORT jint JNICALL Java_uk_co_therhys_LibYT_ytJNI_List_1t_1length_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct List *arg1 = (struct List *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct List **)&jarg1; 
  result = (int) ((arg1)->length);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_uk_co_therhys_LibYT_ytJNI_new_1List_1t(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct List *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct List *)calloc(1, sizeof(struct List));
  *(struct List **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_uk_co_therhys_LibYT_ytJNI_delete_1List_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct List *arg1 = (struct List *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct List **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_uk_co_therhys_LibYT_ytJNI_videos_1free(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  List_t *arg1 = (List_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(List_t **)&jarg1; 
  videos_free(arg1);
}


SWIGEXPORT void JNICALL Java_uk_co_therhys_LibYT_ytJNI_channels_1free(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  List_t *arg1 = (List_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(List_t **)&jarg1; 
  channels_free(arg1);
}


SWIGEXPORT jint JNICALL Java_uk_co_therhys_LibYT_ytJNI_list_1length(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  List_t *arg1 = (List_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(List_t **)&jarg1; 
  result = (int)list_length(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_uk_co_therhys_LibYT_ytJNI_videos_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jlong jresult = 0 ;
  List_t *arg1 = (List_t *) 0 ;
  int arg2 ;
  struct Video *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(List_t **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (struct Video *)videos_get(arg1,arg2);
  *(struct Video **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_uk_co_therhys_LibYT_ytJNI_channels_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jlong jresult = 0 ;
  List_t *arg1 = (List_t *) 0 ;
  int arg2 ;
  struct Channel *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(List_t **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (struct Channel *)channels_get(arg1,arg2);
  *(struct Channel **)&jresult = result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

