/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package uk.co.therhys.LibYT;

public class ytJNI {
  public final static native void Channel_t_id_set(long jarg1, String jarg2);
  public final static native String Channel_t_id_get(long jarg1);
  public final static native void Channel_t_name_set(long jarg1, String jarg2);
  public final static native String Channel_t_name_get(long jarg1);
  public final static native void Channel_t_sub_count_set(long jarg1, int jarg2);
  public final static native int Channel_t_sub_count_get(long jarg1);
  public final static native void Channel_t_video_count_set(long jarg1, int jarg2);
  public final static native int Channel_t_video_count_get(long jarg1);
  public final static native long new_Channel_t();
  public final static native void delete_Channel_t(long jarg1);
  public final static native void Channels_t_arry_set(long jarg1, long jarg2);
  public final static native long Channels_t_arry_get(long jarg1);
  public final static native void Channels_t_length_set(long jarg1, int jarg2);
  public final static native int Channels_t_length_get(long jarg1);
  public final static native long new_Channels_t();
  public final static native void delete_Channels_t(long jarg1);
  public final static native long channel_new(String jarg1);
  public final static native String vid_get_thumbnail(long jarg1);
  public final static native long channel_new_from_name(String jarg1, long jarg2);
  public final static native void channel_search(long jarg1, String jarg2, int jarg3, long jarg4, long jarg5);
  public final static native long channel_search_list(long jarg1, String jarg2, int jarg3);
  public final static native String channel_name(long jarg1, long jarg2);
  public final static native int channel_get_vids(long jarg1, long jarg2, long jarg3, long jarg4);
  public final static native long channel_get_vids_list(long jarg1, long jarg2);
  public final static native void channel_free(long jarg1);
  public final static native void Config_t_fname_set(long jarg1, String jarg2);
  public final static native String Config_t_fname_get(long jarg1);
  public final static native void Config_t_quality_set(long jarg1, int jarg2);
  public final static native int Config_t_quality_get(long jarg1);
  public final static native void Config_t_subs_set(long jarg1, long jarg2);
  public final static native long Config_t_subs_get(long jarg1);
  public final static native void Config_t_invidious_inst_set(long jarg1, String jarg2);
  public final static native String Config_t_invidious_inst_get(long jarg1);
  public final static native void Config_t_use_threading_set(long jarg1, int jarg2);
  public final static native int Config_t_use_threading_get(long jarg1);
  public final static native void Config_t_use_proxy_set(long jarg1, int jarg2);
  public final static native int Config_t_use_proxy_get(long jarg1);
  public final static native void Config_t_proxy_url_set(long jarg1, String jarg2);
  public final static native String Config_t_proxy_url_get(long jarg1);
  public final static native long new_Config_t();
  public final static native void delete_Config_t(long jarg1);
  public final static native long config_new(String jarg1, int jarg2);
  public final static native void config_subs_add(long jarg1, long jarg2);
  public final static native void config_subs_rm(long jarg1, long jarg2);
  public final static native void config_save(long jarg1);
  public final static native long config_get_vids_list(long jarg1);
  public final static native int config_get_vids(long jarg1, long jarg2, long jarg3);
  public final static native String video_get_playable(long jarg1, long jarg2);
  public final static native void config_free(long jarg1);
  public final static native void config_video_search(long jarg1, String jarg2, int jarg3, long jarg4, long jarg5);
  public final static native long config_video_search_list(long jarg1, String jarg2, int jarg3);
  public final static native void Video_t_id_set(long jarg1, String jarg2);
  public final static native String Video_t_id_get(long jarg1);
  public final static native void Video_t_title_set(long jarg1, String jarg2);
  public final static native String Video_t_title_get(long jarg1);
  public final static native void Video_t_channel_name_set(long jarg1, String jarg2);
  public final static native String Video_t_channel_name_get(long jarg1);
  public final static native void Video_t_channel_id_set(long jarg1, String jarg2);
  public final static native String Video_t_channel_id_get(long jarg1);
  public final static native void Video_t_thumbnail_set(long jarg1, String jarg2);
  public final static native String Video_t_thumbnail_get(long jarg1);
  public final static native void Video_t_published_set(long jarg1, int jarg2);
  public final static native int Video_t_published_get(long jarg1);
  public final static native long new_Video_t();
  public final static native void delete_Video_t(long jarg1);
  public final static native long video_new();
  public final static native void video_free(long jarg1);
  public final static native void List_t_arry_set(long jarg1, long jarg2);
  public final static native long List_t_arry_get(long jarg1);
  public final static native void List_t_length_set(long jarg1, int jarg2);
  public final static native int List_t_length_get(long jarg1);
  public final static native long new_List_t();
  public final static native void delete_List_t(long jarg1);
  public final static native void videos_free(long jarg1);
  public final static native void channels_free(long jarg1);
  public final static native int list_length(long jarg1);
  public final static native long videos_get(long jarg1, int jarg2);
  public final static native long channels_get(long jarg1, int jarg2);
}
